# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BayesActMessage.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='BayesActMessage.proto',
  package='EHwA',
  serialized_pb='\n\x15\x42\x61yesActMessage.proto\x12\x04\x45HwA\"\\\n\x0f\x42\x61yesActRequest\x12\x12\n\nevaluation\x18\x01 \x02(\x01\x12\x0f\n\x07potency\x18\x02 \x02(\x01\x12\x10\n\x08\x61\x63tivity\x18\x03 \x02(\x01\x12\x12\n\nhandAction\x18\x04 \x02(\x05\"X\n\x0f\x42\x61yesActRespond\x12\x12\n\nevaluation\x18\x01 \x02(\x01\x12\x0f\n\x07potency\x18\x02 \x02(\x01\x12\x10\n\x08\x61\x63tivity\x18\x03 \x02(\x01\x12\x0e\n\x06prompt\x18\x04 \x02(\x05')




_BAYESACTREQUEST = _descriptor.Descriptor(
  name='BayesActRequest',
  full_name='EHwA.BayesActRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='evaluation', full_name='EHwA.BayesActRequest.evaluation', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='potency', full_name='EHwA.BayesActRequest.potency', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='activity', full_name='EHwA.BayesActRequest.activity', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='handAction', full_name='EHwA.BayesActRequest.handAction', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=31,
  serialized_end=123,
)


_BAYESACTRESPOND = _descriptor.Descriptor(
  name='BayesActRespond',
  full_name='EHwA.BayesActRespond',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='evaluation', full_name='EHwA.BayesActRespond.evaluation', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='potency', full_name='EHwA.BayesActRespond.potency', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='activity', full_name='EHwA.BayesActRespond.activity', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='prompt', full_name='EHwA.BayesActRespond.prompt', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=125,
  serialized_end=213,
)

DESCRIPTOR.message_types_by_name['BayesActRequest'] = _BAYESACTREQUEST
DESCRIPTOR.message_types_by_name['BayesActRespond'] = _BAYESACTRESPOND

class BayesActRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _BAYESACTREQUEST

  # @@protoc_insertion_point(class_scope:EHwA.BayesActRequest)

class BayesActRespond(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _BAYESACTRESPOND

  # @@protoc_insertion_point(class_scope:EHwA.BayesActRespond)


# @@protoc_insertion_point(module_scope)
